### ISSUE TITLE
Installing over an existing copy throws error

### ISSUE THREAD

**Issue by itomek** [pulsebridge/uber#2] opened 2015-11-21 00:49 UTC
HI, I am getting the following error when I try to install:

```
user@machine : ~/src/GitHub/uber
 [master] ==> ./install 
-bash(19335,0x7fff75675000) malloc: *** error for object 0x7f9162507490: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

so I  did:

```
user@machine : ~
 ==> mv .ssh .ssh.old

user@machine : ~
 ==> cd src/GitHub/uber/

user@ machine : ~/src/GitHub/uber
 [master] ==> ./install 
cp: /Users/user/.ssh/*: No such file or directory
```

This created a new .ssh directory for me. I ended up removing the new .ssh directory and renaming my .ssh.old back to .ssh.

I then went into the .ssh directory and removed all of the traces of the old version of uber, closed the terminal window, opened a new terminal window and then ran the install again. That worked.

**Comment by dmccaffery** [comment] 2015-11-21 00:54
This seems to be caused by a race condition whereby the git-prompt function is running while the file is being over-written by the new version. I'll have to look at ways of resolving the issue for those who already have the prompt installed.

**Comment by dmccaffery** [comment] 2015-11-21 02:24
Should be resolved. It was a race condition.

**Closed by dmccaffery** 2015-11-21 02:24 UTC
